spring:
  application:
    name: EmployeeSearch
  
  
  cloud:
    config:
      uri: http://localhost:8881
      
server:
  port: 8882

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka
  instance:
    hostname: localhost
    
