spring:
  application:
    name: EmployeeAPIGateway

server:
  port: 8883

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka
  instance:
    hostname: localhost

    
